server:
  port: 8080

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:mysql://localhost:3306/online_bookstore
    username: root
    password: Ab@230596
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: optional:configserver:http://
    import-check:
      enabled: false
  flyway:
    baseline-on-migrate: true
    out-of-order: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
