server:
  port: 8081

spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://
    import-check:
      enabled: false
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: online_bookstore
      port: 27017
      host: mongodb

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# configure tracing
management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

