server:
  port: 8081

spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://
    import-check:
      enabled: false
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: online_bookstore
      port: 27017
      host: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
