server:
  port: 8081

spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://
    import-check:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
